# Generated by Django 4.1.1 on 2022-09-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BaseDeDatos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id_historia', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_pac', models.CharField(max_length=40)),
                ('apellido_pac', models.CharField(max_length=40)),
                ('fecha_hist', models.DateField()),
                ('diagnostico', models.CharField(max_length=200)),
            ],
        ),
    ]
